name: Building Docker images

on:
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    main:
        strategy:
            matrix:
                include:
                    - name: "Ubuntu OpenMPI g++"
                      compiler: gcc
                      mpi: openmpi
                      os: ubuntu
                    - name: "Ubuntu MPICH g++"
                      compiler: gcc
                      mpi: mpich
                      os: ubuntu
                    - name: "Debian OpenMPI g++"
                      compiler: gcc
                      mpi: openmpi
                      os: debian
                    - name: "Debian MPICH g++"
                      compiler: gcc
                      mpi: mpich
                      os: debian
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[main skip]')"
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push ${{ matrix.name }}
              uses: docker/build-push-action@v2
              with:
                  push: true
                  file: ./${{ matrix.os }}/Dockerfile.${{ matrix.compiler }}
                  target: ${{ matrix.os }}_${{ matrix.mpi }}
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:${{ matrix.os }}_${{ matrix.compiler }}_${{ matrix.mpi }}
                  cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:${{ matrix.os }}_${{ matrix.compiler }}_${{ matrix.mpi }}
                  build-args: BUILDKIT_INLINE_CACHE=1
