name: Building Docker images

on:
  push:
    branches: master

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            # -
            #     name: Cache Docker layers
            #     uses: actions/cache@v2
            #     with:
            #       path: /tmp/.buildx-cache-ubuntu-openmpi
            #       key: ${{ runner.os }}-buildx-${{ github.sha }}
            #       restore-keys: |
            #         ${{ runner.os }}-buildx-
                        
            -
                name: Login to DockerHub
                uses: docker/login-action@v1 
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -
                name: Build and push Ubuntu image with openmpi
                uses: docker/build-push-action@v2
                with:
                    push: true
                    pull: true
                    file: ./Ubuntu/Dockerfile
                    target: ubuntu_openmpi
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:ubuntu_openmpi
                    cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:ubuntu_openmpi
                    # cache-to: type=local,dest=/tmp/.buildx-cache

            -
                name: Build and push Ubuntu image with mpich
                uses: docker/build-push-action@v2
                with:
                    push: true
                    pull: true
                    file: ./Ubuntu/Dockerfile
                    target: ubuntu_mpich
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:ubuntu_mpich
                    # cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:ubuntu_mpich
                    # cache-to: type=local,dest=/tmp/.buildx-cache

            -
                name: Build and push Debian image with openmpi
                uses: docker/build-push-action@v2
                with:
                    push: true
                    pull: true
                    file: ./Debian/Dockerfile
                    target: debian_openmpi
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:debian_openmpi
                    # cache-from: type=local,src=/tmp/.buildx-cache
                    # cache-to: type=local,dest=/tmp/.buildx-cache

            -
                name: Build and push Debian image with mpich
                uses: docker/build-push-action@v2
                with:
                    push: true
                    pull: true
                    file: ./Debian/Dockerfile
                    target: debian_mpich
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:debian_mpich
                    # cache-from: type=local,src=/tmp/.buildx-cache
                    # cache-to: type=local,dest=/tmp/.buildx-cache