name: Building Docker images

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    strategy:
      matrix:
        include:
          - name: "Ubuntu gcc OpenMPI"
            cc: gcc
            cxx: g++
            mpi: openmpi
            os: ubuntu
          - name: "Ubuntu clang OpenMPI"
            cc: clang
            cxx: clang++
            mpi: openmpi
            os: ubuntu
          - name: "Ubuntu gcc MPICH"
            cc: gcc
            cxx: g++
            mpi: mpich
            os: ubuntu
          - name: "Ubuntu clang MPICH"
            cc: clang
            cxx: clang++
            mpi: mpich
            os: ubuntu
          - name: "Ubuntu gcc OpenMPI"
            cc: gcc
            cxx: g++
            mpi: openmpi
            os: debian
          - name: "Ubuntu clang OpenMPI"
            cc: clang
            cxx: clang++
            mpi: openmpi
            os: debian
          - name: "Ubuntu gcc MPICH"
            cc: gcc
            cxx: g++
            mpi: mpich
            os: debian
          - name: "Ubuntu clang MPICH"
            cc: clang
            cxx: clang++
            mpi: mpich
            os: debian

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[main skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./${{ matrix.os }}/Dockerfile
          target: ${{ matrix.os }}_${{ matrix.cxx }}_${{ matrix.mpi }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:${{ matrix.os }}_${{ matrix.mpi }}
          cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:${{ matrix.os }}_${{ matrix.cxx }}_${{ matrix.mpi }}
          build-args: BUILDKIT_INLINE_CACHE=1
