name: Building Docker images

on:
  push:
    branches: [master]

jobs:
    main:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[main skip]')"
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
  
            -
                name: Login to DockerHub
                uses: docker/login-action@v1 
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -
                name: Build and push Ubuntu image with openmpi
                uses: docker/build-push-action@v2
                with:
                    push: true
                    file: ./Ubuntu/Dockerfile
                    target: ubuntu_openmpi
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:ubuntu_openmpi
                    cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:ubuntu_openmpi
                    build-args: BUILDKIT_INLINE_CACHE=1

            -
                name: Build and push Ubuntu image with mpich
                uses: docker/build-push-action@v2
                with:
                    push: true
                    file: ./Ubuntu/Dockerfile
                    target: ubuntu_mpich
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:ubuntu_mpich
                    cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:ubuntu_mpich
                    build-args: BUILDKIT_INLINE_CACHE=1

            -
                name: Build and push Debian image with openmpi
                uses: docker/build-push-action@v2
                with:
                    push: true
                    file: ./Debian/Dockerfile
                    target: debian_openmpi
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:debian_openmpi
                    cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:debian_openmpi
                    build-args: BUILDKIT_INLINE_CACHE=1

            -
                name: Build and push Debian image with mpich
                uses: docker/build-push-action@v2
                with:
                    push: true
                    file: ./Debian/Dockerfile
                    target: debian_mpich
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:debian_mpich
                    cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/htool_testing_environments:debian_mpich
                    build-args: BUILDKIT_INLINE_CACHE=1